export const refundRequest = [{
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 250,
  status: "예약확정",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}, {
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 250,
  status: "예약확정",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}, {
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 24,
  status: "주문처리중",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}, {
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 250,
  status: "주문처리중",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}, {
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 250,
  status: "주문처리중",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}, {
  orderNo: "6ed34Edf65d",
  shopName: "하나투어",
  amount: 450,
  status: "주문처리중",
  name: "상품",
  image: "/assets/images/products/Package/img.png"
}];